### ISSUE TITLE
Error when assembling the library for iOS simulator on MacOS

### ISSUE THREAD

**Issue by GhxstlyJared** [holepunchto/bare-ios#2]
I am trying to build this example for the ios simulator on a MacOS.

After cloning this repo and running:

```
npm i -g bare-runtime
```
```
npm i -g bare-dev
```
```
bare-dev --verbose configure --debug --simulator -p ios
```
I get the following output:

```
CMake Error at CMakeLists.txt:11 (add_subdirectory):
  The source directory

    /bare-ios/vendor/bare-kit

  does not contain a CMakeLists.txt file.
```

I'm not sure if they're doing this correctly, but the problem is the empty bare-kit folder, I tried running
` npx bare-dev vendor sync
`, but got the error:

Cloning to «/bare-ios/vendor/bare-kit»...
git@github.com: Permission denied (publickey).

**Comment by GhxstlyJared** [comment]
Also i don't quite understand the need for cross-compiling the library for iOS since the "ios.toolchain.cmake" file is not specified. Should it be added manually?

**Comment by GhxstlyJared** [comment]
> I'm not sure if they're doing this correctly, but the problem is the empty bare-kit folder, I tried running `npx bare-dev vendor sync`, but got the error:
> 
> Cloning to «/bare-ios/vendor/bare-kit»... [git@github.com](mailto:git@github.com): Permission denied (publickey).

I figure out with this issue by changing two files:
1. bare-ios/.gitmodules:

```
[submodule "vendor/bare-kit"]
	path = vendor/bare-kit
	url = https://github.com/holepunchto/bare-kit.git
```

2. bare-ios/.git/config:

```
[submodule "vendor/bare-kit"]
	active = true
	url = https://github.com/holepunchto/bare-kit.git
```

**Comment by GhxstlyJared** [comment]
I would also like to understand: the example uses the file "main.bundle.h", but it is not in the repository. Is this exactly the file we intend to run (main.js but compiled), or is there an error here and we need to use "worklet.bundle.h"?

**Comment by GhxstlyJared** [comment]
I have already solved all the problems described above, but now I get an error in runtime
I solved all the problems with assembling bare-ios and integrated all the necessary files into the project, using your file [“AppDelegate.m”](https://github.com/holepunchto/bare-ios/blob/main/app/AppDelegate.m) I launch the bare-kit, but the error occurs:

```
Uncaught Error: No addon registered for 'bare-os@2.3.0'
    at Object.addon (bare:67:23)
    at require.addon (bare:7:17)
    at require.addon (bare:14540:87)
    at Object.source (bare:14388:190)
    at Object.require (bare:14543:9)
    at require (bare:14547:27)
    at Object.source (bare:11924:338)
    at Object.require (bare:14543:9)
    at require (bare:14547:27)
    at Object.source (bare:10540:382)
```

   Tell me, maybe i need to write some commands to load node_modules before assembly?

**Comment by kasperisager** [comment]
Everything works on my end. For reference, these are the steps for making an iOS simulator build:

```console
$ bare-dev vendor sync
...
$ bare-dev configure --platform ios --simulator
...
$ bare-dev build
...
$ bare-dev ios run --attach
bare: 6251
2024-06-26 15:21:23.893 Bare[6251:18975507] Hello from Bare
Hello from iOS
```

**Comment by GhxstlyJared** [comment]
> ```
> bare-dev ios run --attach
> ```

Yes, this method also worked successfully for me, thank you. But I'm now trying to assemble this into Xcode proj on real device (arm64), but in runtime the project cannot find "bare-os", there are no auxiliary errors, although in "node_modules" "bare-os" is present with the required version

**Comment by kasperisager** [comment]
We only support using CMake as a build system generator so if you bail out of that there will obviously be dragons 😛 You shouldn't expect to be able to copy intermediate build artefacts out of the build tree and into other build systems.

If you _really_ want to use Xcode you might have better luck with the Xcode generator in CMake, which can be selected using:

```console
$ bare-dev configure --platform ios --generator xcode
```

That'll configure a build tree for an iOS device, not the simulator, using Xcode as the build system. You can open the resulting `.xcodeproj`  in Xcode, but beware that it'll be incredibly slow and may or may not build successfully.
