### ISSUE TITLE
How could I run simple demo

### ISSUE THREAD

**Issue by jj10133** [holepunchto/bare-ios#4]
Any docs on running the app?

**Comment by kasperisager** [comment]
See https://github.com/holepunchto/bare-ios/blob/main/.github/workflows/test.yml for build steps. Once the `.app` has been built, you'd run it like you would any other app using either `simctl` or Xcode.

`bare-dev` has a convenience wrapper for installing and running apps using `simctl`:

```console
bare-dev ios run
```

Pass `--verbose` to see the exact `simctl` commands invoked.
