### ISSUE TITLE
How to integrate bare-ios

### ISSUE THREAD

**Issue by jj10133** [holepunchto/bare-ios#6]
Like I currently have swift project, would like to embed pear runtime in it to access hyperswarm however I don't know more on how to integrate it

**Comment by kasperisager** [comment]
Bare Kit doesn't provide a first-class Swift module, but you can most likely call into the resulting framework using a bridging header. Also note that Bare isn't the same as Pear; Pear uses Bare, but also provides additional APIs on top.

Keep in mind that this repo is a template, not a library. You clone it and adjust it to your needs, you don't integrate it per se.

**Comment by kasperisager** [comment]
Swift is now used for the main application class: https://github.com/holepunchto/bare-ios/blob/main/app/App.swift
