### ISSUE TITLE
Trying to make .xcodeproj file

### ISSUE THREAD

**Issue by jj10133** [holepunchto/bare-ios#7]
Was trying to play around, trying to learn more on cmake... found that missing ios.cmake and bare.cmake that lead me to bare-dev

So just wondering on how bare-dev is configured?

**Comment by kasperisager** [comment]
This template uses CMake as that's what the rest of our native tooling is built around. Take a look at https://github.com/holepunchto/bare-expo for a non-CMake based project that also allows generating Xcode and Android Studio project files through Expo prebuild (https://docs.expo.dev/workflow/prebuild/).

**Comment by kasperisager** [comment]
Heads up that as of latest `main` https://github.com/holepunchto/bare-ios/blob/main/project.yml is used for generating an `.xcodeproj` project manifest.
